accounts/urls.py
from os import name
from django.urls import path
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _
from . import views


urlpatterns = [
  path(_('login/'), views.user_login, name='login'),
  path(_('logout/'), auth_views.LogoutView.as_view(), name='logout'),
  path(_('register/'), views.register, name='register'),
  path(_('profile/'), views.profile, name='profile'),
  
  path(_('password_change/'), auth_views.PasswordChangeView.as_view(),
    name='password_change'),
  
  path(_('password_change/done/'), auth_views.PasswordChangeDoneView.as_view(),
    name='password_change_done'),
  
  path(_('password_reset/'), auth_views.PasswordResetView.as_view(), 
    name='password_reset'),

  path(_('password_reset/done/'), auth_views.PasswordResetDoneView.as_view(),
    name='password_reset_done'),

  path('password_reset/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(), 
    name='password_reset_confirm'),
  
  path(_('password_reset/complete/'), 
    auth_views.PasswordResetCompleteView.as_view(),
    name='password_reset_complete'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from django.utils.translation import gettext_lazy as _
from shl_project.decorators import user_created_order
from . import views


app_name = 'orders'

urlpatterns = [
  path(_('create/'), views.order_create, name='order_create'),
  path('admin/order/<int:order_id>/pdf/', 
    staff_member_required(views.invoice_pdf), name='invoice_pdf'),
  path('order/<int:order_id>/', 
    user_created_order(views.order_detail), name='order_detail'),
  path('order/<int:order_id>/pdf/', 
    user_created_order(views.invoice_pdf), name='customer_invoice_pdf'),
]

shl_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
#from orders.views import apple_pay


urlpatterns = i18n_patterns(
    #path('.well-known/apple-developer-merchantid-domain-association/', apple_pay),
    path(_('accounts/'), include('accounts.urls')),
    path('social-auth/', 
        include('social_django.urls', namespace='social')),
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('listings.urls', namespace='listings'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

shlproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):

  user = models.OneToOneField(
    settings.AUTH_USER_MODEL, on_delete=models.CASCADE
  )
  phone_number = models.CharField(max_length=20, blank=True)
  address = models.CharField(max_length=100, blank=True)
  postal_code = models.CharField(max_length=20, blank=True)
  city = models.CharField(max_length=100, blank=True)
  country = models.CharField(max_length=100, blank=True)

  def __str__(self):
    return f'{self.user.username} profile'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets
from .models import Profile


class LoginForm(forms.Form):

  email = forms.CharField(widget=forms.EmailInput(
    attrs={'class': 'form-control'}
  ))
  password = forms.CharField(widget=forms.PasswordInput(
    attrs={'class': 'form-control'}
  ))


class UserRegistarionForm(forms.ModelForm):

  password2 = forms.CharField(widget=forms.PasswordInput(
    attrs={'class': 'form-control'}
  ))

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'email', 'password')

    widgets = {
      'first_name': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'last_name': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'email': forms.EmailInput(
        attrs={'class': 'form-control'}
      ),
      'password': forms.PasswordInput(
        attrs={'class': 'form-control'}
      )
    }


class UpdateUserForm(forms.ModelForm):

  class Meta:
    model = User
    fields = ('first_name', 'last_name', 'email')

    widgets = {
      'first_name': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'last_name': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'email': forms.EmailInput(
        attrs={'class': 'form-control'}
      )
    }


class UpdateUserProfileForm(forms.ModelForm):

  class Meta:
    model = Profile
    fields = ('phone_number', 'address', 'postal_code', 'city', 'country')

    widgets = {
      'phone_number': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'address': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'postal_code': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'city': forms.TextInput(
        attrs={'class': 'form-control'}
      ),
      'country': forms.TextInput(
        attrs={'class': 'form-control'}
      )
    }

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from .models import Profile
from .forms import (
  LoginForm, UserRegistarionForm, UpdateUserForm, UpdateUserProfileForm
)


def user_login(request):

  if request.method == 'POST':
    form = LoginForm(request.POST)

    if form.is_valid():
      cf = form.cleaned_data
      user_record = None
      try:
        user_record = User.objects.get(email=cf['email'])
      except User.DoesNotExist:
        pass

      if user_record:
        user = authenticate(request, 
          username=user_record, password=cf['password']
        )
        
        if user is not None:
          login(request, user)

          return redirect('listings:product_list')
      
      messages.error(request, _('Incorrect email / password'))
  
  else:
    form = LoginForm()
  
  return render(request, 'accounts/login.html', {'form': form})


def register(request):

  if request.method == 'POST':
    user_form = UserRegistarionForm(request.POST)

    if user_form.is_valid():
      cf = user_form.cleaned_data
      
      email = cf['email']
      password = cf['password']
      password2 = cf['password2']

      if password == password2:
        
        if User.objects.filter(email=email).exists():
          messages.error(request,
            _('User with given email already exists'))
            
          return render(request, 'accounts/register.html', {'user_form': user_form})
        
      else:
        messages.error(request, 'Passwords don\'t match')

        return render(request, 'accounts/register.html', {'user_form': user_form})
        
      new_user = User.objects.create_user(
        first_name=cf['first_name'], last_name=cf['last_name'],
        username=email, email=email, password=password
      )
      Profile.objects.create(user=new_user)

      return render(request, 'accounts/register_done.html', {'new_user': new_user})
  
  else:
    user_form = UserRegistarionForm()
  
  return render(request, 'accounts/register.html', {'user_form': user_form})


@login_required
def profile(request):

  if request.method == 'POST':
    email = request.POST['email']
    user = None

    try:
      user = User.objects.get(email=email)
    except User.DoesNotExist:
      pass

    if user is None or user.id == request.user.id:
      user_form = UpdateUserForm(
        instance=request.user, data=request.POST
      )
      profile_form = UpdateUserProfileForm(
        instance=request.user.profile, data=request.POST
      )
      if user_form.is_valid() and profile_form.is_valid():
        user_form.save()
        profile_form.save()

        messages.success(request, _('Profile was updated successfully'))
    
    else:
      messages.error(request, _('User with given email already exists'))
    
    return redirect('profile')
  
  else:
    user_form = UpdateUserForm(instance=request.user) 
    try:
      profile_form = UpdateUserProfileForm(instance=request.user.profile)
    except:
      Profile.objects.create(user=request.user)
      profile_form = UpdateUserProfileForm(instance=request.user.profile)
  
  return render(request, 'accounts/profile.html', {
    'user_form': user_form, 'profile_form': profile_form
  })

templates/accounts/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Log in' %}{% endblock %}

{% block content %}

{% if messages %}
  <div class="shadow-custom messages alert alert-danger
    col-lg-4 mx-auto text-center">
    {% for message in messages %}
      {{ message }}
      <a href="" class="close">x</a>
    {% endfor %}
  </div>
{% endif %}

<div class="card shadow-custom border-0 col-lg-4 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">{% trans 'Log in' %}</h3>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="input-field">
      {{ form.email }}
      <label for="email">{% trans 'Email' %}</label>
    </div>
    <div class="input-field">
      {{ form.password }}
      <label for="password">{% trans 'Password' %}</label>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
      {% trans 'Log in' %}
    </button>
  </form>
  <div class="text-center mb-2">
    <a href="{% url 'password_reset' %}"
      class="text-decoration-none">
      {% trans 'Forgot your password?' %}
    </a>
  </div>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account' %}{% endblock %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="shadow-custom messages alert alert-danger text-center
      col-lg-7 mx-auto">
    {% else %}
    <div class="shadow-custom messages alert alert-success text-center
      col-lg-7 mx-auto">
    {% endif %}
      {{ message }}
      <a href="" class="close">x</a>
    </div>
  {% endfor %}
{% endif %}
  <div class="card shadow-custom border-0 col-lg-7 mx-auto mb-3">
    <h2 class="font-weight-bold text-grey mt-2">{% trans 'Profile' %}</h2>
    <form action="" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.first_name }}
            <label for="first_name">{% trans 'First name' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.last_name }}
            <label for="last_name">{% trans 'Last name' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ user_form.email }}
            <label for="email">{% trans 'Email' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.phone_number }}
            <label for="phone_number">{% trans 'Phone number' %}</label>
          </div>
        </div>
      </div>
      <hr class="mt-0">
      <div class="row">
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.address }}
            <label for="address">{% trans 'Address' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.postal_code }}
            <label for="postal_code">{% trans 'Postal code' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.city }}
            <label for="city">{% trans 'City' %}</label>
          </div>
        </div>
        <div class="col-md-6">
          <div class="input-field">
            {{ profile_form.country }}
            <label for="country">{% trans 'Country' %}</label>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-6 text-center">
          <button type="submit" class="btn btn-dark" data-toggle="tooltip" 
            data-placement="top"
            title="Fill in new details and click 'Update profile'">
            {% trans 'Update profile' %}</button>
        </div>
        <div class="col-md-6 text-center">
          <a class="btn btn-warning" href="{% url 'password_change' %}">
            {% trans 'Change password' %}
          </a>
        </div>
      </div>
      <hr>
      <h3 class="mb-3">{% trans 'Your orders' %}:</h3>
      <table class="table">
        {% for order in request.user.orders.all %}
          <tr>
            <td>
              <a href="{{ order.get_absolute_url }}" 
                class="text-decoration-none">
                {{ order.id }}
              </a>
            </td>
            <td>{{order.created|date }}</td>
            <td class="text-green">
              ${{ order.get_total_cost|floatformat:2 }}
            </td>
            <td>
              <a href="{% url 'orders:customer_invoice_pdf' order.id %}" 
                class="text-decoration-none" target="_blank">
                <i class="far fa-file-pdf text-danger"></i>
                {% trans 'Invoice' %} {{ order.id }}
              </a>
            </td>
            <td>{{ order.status }}</td>
          </tr>
        {% empty %}
          <tr>
            {% trans 'No orders yet.' %}
          </tr>
        {% endfor %}
      </table>
    </form>
  </div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Register' %}{% endblock %}

{% block content %}

{% if messages %}
  <div class="shadow-custom messages alert alert-danger
    col-lg-5 mx-auto text-center">
    {% for message in messages %}
      {{ message }}
      <a href="" class="close">x</a>
    {% endfor %}
  </div>
{% endif %}

<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">
    {% trans 'Register' %}
  </h3>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <div class="input-field">
        {{ user_form.first_name }}
        <label for="first_name">{% trans 'First name' %}</label>
      </div>
      <div class="input-field">
        {{ user_form.last_name }}
        <label for="last_name">{% trans 'Last name' %}</label>
      </div>
      <div class="input-field">
        {{ user_form.email }}
        <label for="email">{% trans 'Email' %}</label>
      </div>
      <div class="input-field">
        {{ user_form.password }}
        <label for="password">{% trans 'Password' %}</label>
      </div>
      <div class="input-field">
        {{ user_form.password2 }}
        <label for="password2">{% trans 'Repeat password' %}</label>
      </div>
    </div>
    <button class="btn btn-block btn-warning mb-3" type="submit">
      {% trans 'Register' %}
    </button>
  </form>
</div>

<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3">
  <h3 class="py-2 font-weight-bold text-grey text-center">
    {% trans 'Register with social account' %}
  </h3>
  <a href="{% url 'social:begin' 'twitter' %}" 
    class="btn btn-block btn-outline-primary mb-3"
    role="button" aria-pressed="true">
    <i class="fab fa-twitter"></i> {% trans 'Register with Twitter' %}
  </a>
  <a href="{% url 'social:begin' 'google-oauth2' %}"
    class="btn btn-block btn-outline-success mb-3"
    role="button" aria-pressed="true">
    <i class="fab fa-google"></i> {% trans 'Register with Google' %}
  </a>
  <hr>
  <div class="align-self-center">
    <span class="text-center font-weight-bold text-muted">
      {% trans 'After successful log-in' %},<br> 
      {% trans 'we highly recommend that' %}<br> 
      {% trans 'you enter your profile information' %}.<br>
    </span>
  </div>
</div>
{% endblock %}

templates/accounts/register_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Registration Complete' %}{% endblock %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-5 mx-auto mb-3 text-center">
  <h3 class="py-2 font-weight-bold text-grey">
    {% trans 'Welcome' %}, {{ new_user.first_name }}!
  </h3>
  <hr class="my-0">
  <div class="py-2">
    {% trans 'Your account was successfully created.' %}
    {% trans 'You can' %} <a href="{% url 'login' %}">{% trans 'log in' %}</a> {% trans 'now' %}.
  </div>
</div>
{% endblock %}