cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

listings/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views


app_name = 'listings'

urlpatterns = [
  path('', views.product_list, name='product_list'),

  path(_('favorite/'), views.product_fav, name='favorite'),
  
  path('<slug:category_slug>/', views.product_list, 
    name='product_list_by_category'),
  
  path('<slug:category_slug>/<slug:product_slug>/',
    views.product_detail, name='product_detail'),
]

shl_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
#from orders.views import apple_pay


urlpatterns = i18n_patterns(
    #path('.well-known/apple-developer-merchantid-domain-association/', apple_pay),
    path(_('accounts/'), include('accounts.urls')),
    path('social-auth/', 
        include('social_django.urls', namespace='social')),
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('listings.urls', namespace='listings'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

shlproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/product/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="card shadow-custom border-0 col-lg-9 mx-auto">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <img src="{{ product.image.url }}" alt="" class="img-fluid rounded-0">
    </div>
    <div class="col-lg-6">
      <div class="top">
        <h2 class="mt-4 font-weight-bold text-grey">
          {{ product.name }}
        </h2>
        {% if product.shu %}
          <div>
            <span class="font-weight-bold text-grey">
              {% trans 'Hotness' %}:
            </span> {{ product.shu }} SHU
          </div>
        {% elif product.abv %}
          <div>
            <span class="font-weight-bold text-grey">
              ABV:
            </span> {{ product.abv }}
          </div>
        {% endif %}
        {% if product.net %}
          <div>
            <span class="font-weight-bold text-grey">
              NET:
            </span> {{ product.net }}
          </div>
        {% endif %}
      </div>
      <div class="mt-3">
        {{ product.description|linebreaks }}
      </div>
      {% if product.available %}
        <div class="alert alert-success my-3 text-center">
          {% trans 'Available' %}
        </div>
      {% else %}
        <div class="alert alert-danger my-3 text-center">
          {% trans 'Currently unavailable' %}
        </div>
      {% endif %}
      <hr>
      {% with total_favs=product.users_fav.count users_favs=product.users_fav.all %}
        <div>
          <span class="count">
            {{ total_favs }} {% trans 'user' %}{{ total_favs|pluralize }}
            {% trans 'liked this product' %}
          </span><br>
          <div class="review mb-3 font-weight-bold">
            <a href="#" data-id="{{ product.id }}"
              data-action="{% if request.user in users_favs %}un{% endif %}like"
              class="like">
              {% if request.user not in users_favs %}
                {% trans 'Add to favorite' %}
              {% else %}
                {% trans 'Remove from favorite' %}
              {% endif %}
            </a>
          </div>
        </div>
      {% endwith %}
      <div class="review">
        <span class="font-weight-bold text-grey">
          {% trans 'Average rating' %}: {{ product.get_average_review_score }}/5.0
        </span>
        <div class="mb-3 font-weight-bold">
          <a href="" class="text-warning" data-toggle="modal" 
            data-target="#myModal">
            {% trans 'Write review' %}
          </a>
        </div>
      </div>
      <div class="mb-4">
        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
          {% csrf_token %}
          <span class="input-group add-to-cart shadow-custom">
            <div class="input-group-prepend">
              <span class="input-group-text font-weight-bold
                px-3 btn btn-block price">
                ${{ product.price }}
              </span>
            </div>
            <span id="minus" class="input-group-text button_minus px-4">
              -
            </span>
            {{ cart_product_form.quantity }}
            <span id="plus" class="input-group-text button_plus px-4">
              +
            </span>
            <div class="input-group-append">
              <button class="btn btn-danger px-4 reduce_padding"
                type="submit" data-toggle="tooltip" data-placement="top"
                title="Add to cart">
                <i class="fas fa-shopping-cart"></i>
              </button>
            </div>
          </span>
        </form>
      </div>
    </div>
  </div>
</div>
<hr class="col-7 mx-auto">
<div class="card shadow-custom border-0 col-lg-9 mx-auto mb-3">
  <h3 class="py-2 text-grey">{% trans 'Reviews' %}:</h3>
  {% for review in product.reviews.all %}
    <span class="font-weight-bold py-2 text-grey">
      {{ review.author }} - {{ review.rating }}/5 - {{ review.created|date }}
    </span>
    <span class="text-justify pb-2">
      {{ review.text|linebreaks }}
    </span>
    <hr>
  {% empty %}
    <span class="pb-2">{% trans 'Currently no reviews' %}</span>
  {% endfor %}
</div>
{% if recommendation %}
  <hr class="col-7 mx-auto">
  <div class="card shadow-custom border-0 col-lg-9 mx-auto mb-3">
    <div class="card-body text-center">
      <h3 class="font-weight-bold text-grey">
        {% trans 'You may also like...' %}
      </h3>
      <div class="bottom_line"></div>
    </div>
  </div>
  <div class="row no-gutters justify-content-center">
    {% for p in recommendation %}
      <div class="col-sm-3">
        <div class="card product h-100">
          <div class="item">
            <div class="item-image">
              <img src="{{ p.image.url }}" alt="" class="img-fluid rounded-0">
            </div>
            <div class="item-text">
              <div class="item-text-wrap">
                <a href="{{ p.get_absolute_url }}"
                  class="h2 text-white text-decoration-none">
                  <i class="fas fa-search-plus"></i>
                </a>
              </div>
            </div>
            <div class="card-body text-center">
              {{ p.name }}
              <hr>
              <span><i class="fas fa-thin fa-dollar-sign"></i>
                {{ p.price }}
              </span>
              <div>
                <i class="fas fa-shopping-basket"></i>
                  {{ p.net }}
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}

<!-- MODAL -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">{% trans 'Write your review' %}</h5>
        <button class="close" data-dismiss="modal">&times;</button>
      </div>
      <form method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="bg-grey">
            <div class="text-center pt-2">
              {% trans 'Rating' %}:
              <div id="full-stars" class="d-inline text-center">
                <div class="rating-group">
                  <label class="rating__label" for="id_rating_0">
                    <i class="rating__icon rating__icon--star fa fa-star"></i>
                  </label>
                  <input class="rating__input" name="rating" 
                    id="id_rating_0" value="1" type="radio" required>
              
                  <label class="rating__label" for="id_rating_1">
                    <i class="rating__icon rating__icon--star fa fa-star"></i>
                  </label>
                  <input class="rating__input" name="rating" 
                    id="id_rating_1" value="2" type="radio" required>
              
                  <label class="rating__label" for="id_rating_2">
                    <i class="rating__icon rating__icon--star fa fa-star"></i>
                  </label>
                  <input class="rating__input" name="rating" 
                    id="id_rating_2" value="3" type="radio" required>
              
                  <label class="rating__label" for="id_rating_3">
                    <i class="rating__icon rating__icon--star fa fa-star"></i>
                  </label>
                  <input class="rating__input" name="rating" 
                    id="id_rating_3" value="4" type="radio" required>
              
                  <label class="rating__label" for="id_rating_4">
                    <i class="rating__icon rating__icon--star fa fa-star"></i>
                  </label>
                  <input class="rating__input" name="rating" 
                    id="id_rating_4" value="5" type="radio" checked required>
                </div>
              </div>              
            </div>
            <hr class="m-0">
            <div class="input-field text-center p-2">
              {{ review_form.text }}
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger" type="submit">Confirm</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "listings:favorite" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' :
          'Like');

          // update total likes
          var previous_likes = parseInt($('span.count').text());
          $('span.count').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
        }
      }
    );
  });
{% endblock %}

templates/product/list.html
{% extends 'base.html' %}
{% load listings_tags %}
{% load i18n %}

{% block title %}SHL.depot{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-lg-3">
    <div class="card shadow-custom border-0">
      <h4 class="p-3 font-weight-bold text-grey">{% trans 'Categories' %}</h4>
      <ul class="list-group border-0 categories_list">
        <li 
          {% if not requested_category %}
            class="list-group-item border-0 p-0 selected"
          {% else %}
            class="list-group-item border-0 p-0 unselected"
          {% endif %}>
            <a href="{% url 'listings:product_list' %}" 
              class="btn btn-block text-left">{% trans 'All' %}</a>
        </li>
        {% for category in categories %}
          <li 
            {% if category.slug == requested_category.slug %}
              class="list-group-item border-0 p-0 selected"
            {% else %}
              class="list-group-item border-0 p-0 unselected"
            {% endif %}>
              <a href="{{ category.get_absolute_url }}" 
                class="btn btn-block text-left">
                {{ category.name }}
              </a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <hr><br>
    {% search_bar %}
  </div>
  <div class="col-lg-9">
    <div class="card shadow-custom border-0 mb-4">
      <div class="card-body text-center">
        <h2 class="font-weight-bold text-grey">
          {% if requested_category %}
            {{ requested_category.name }}
          {% elif query %}
            {% trans 'Search results' %}
          {% else %}
            {% trans 'Our Products' %}
          {% endif %}
        </h2>
        <div class="bottom_line"></div>
      </div>
    </div>
    <div class="row no-gutters">
      {% for product in products %}
        <div class="col-sm-4">
          <div class="card product h-100">
            <div class="item">
              <div class="item-image">
                <img src="{{ product.image.url }}" alt=""
                  class="img-fluid rounded-0">
              </div>
              <div class="item-text">
                <div class="item-text-wrap">
                  <a href="{{ product.get_absolute_url }}" 
                    class="h2 text-white text-decoration-none">
                    <i class="fas fa-search-plus"></i>
                  </a>
                </div>
              </div>
              <div class="card-body text-center">
                {{ product.name }}
                <hr>
                <span><i class="fas fa-thin fa-dollar-sign"></i>
                  {{ product.price }}
                </span>
                <div>
                  <i class="fas fa-shopping-basket"></i>
                  {{ product.net }}
                </div>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <div class="col-sm-12">
          <div class="h4 text-decoration-none text-center">
            {% trans 'Sorry, no results found.' %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="col-lg-3"></div>
  <div class="pagination">
    <span class="step-links">
      <i class="fas fa-caret-square-left"></i>
      {% if products.has_previous %}
        <a href="?page={{ products.previous_page_number }}"
          class="text-warning">{% trans 'Back' %}</a>
      {% endif %}
      <span class="current">
        {% trans 'Page' %} {{ products.number }} {% trans 'of' %} {{ products.paginator.num_pages }}
      </span>
      {% if products.has_next %}
        <a href="?page={{ products.next_page_number }}" 
          class="text-warning">{% trans 'Next' %}</a>
      {% endif %}
      <i class="fas fa-caret-square-right"></i>
    </span>
  </div>
</div>
<hr>
{% endblock %}

templates/product/search_bar.html
{% load i18n %}
<form method="GET" action="">
  <div class="input-field">
    <label class="text-muted">
      <i class="fas fa-search"></i>
    </label>
    {{ form.query }}
  </div>
  <button class="btn btn-dark btn-block" type="submit">
    {% trans 'Search' %}
  </button>
</form>