cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
  path('', views.cart_detail, name='cart_detail'),
  path('add/<int:product_id>/', views.cart_add, name='cart_add'),
  path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

listings/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views


app_name = 'listings'

urlpatterns = [
  path('', views.product_list, name='product_list'),

  path(_('favorite/'), views.product_fav, name='favorite'),
  
  path('<slug:category_slug>/', views.product_list, 
    name='product_list_by_category'),
  
  path('<slug:category_slug>/<slug:product_slug>/',
    views.product_detail, name='product_detail'),
]

shl_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
#from orders.views import apple_pay


urlpatterns = i18n_patterns(
    #path('.well-known/apple-developer-merchantid-domain-association/', apple_pay),
    path(_('accounts/'), include('accounts.urls')),
    path('social-auth/', 
        include('social_django.urls', namespace='social')),
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('listings.urls', namespace='listings'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                        document_root=settings.MEDIA_ROOT)

shlproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
{% load i18n %}  
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito&display=swap">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top py-3"
    id="main-nav">
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    <div class="container">
      <a href="{% url 'listings:product_list' %}" class="navbar-brand">
        <h3 class="font-weight-bold">SHL.depot</h3>
      </a>
      {% for language in languages %}
        <a href="/{{ language.code }}/" class="nav-link text-white">
          {{ language.name_local }} 
        </a>
      {% endfor %}
      <button class="navbar-toggler" data-toggle="collapse"
        data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span> 
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'profile' %}" class="nav-link text-white">
                <i class="fas fa-user"></i> {% trans 'Welcome,' %} {{ request.user.first_name }}
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'logout' %}" class="nav-link text-white">
                <i class="fas fa-sign-out-alt"></i> {% trans 'Log out' %}
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link text-white">
                <i class="fas fa-sign-in-alt"></i> {% trans 'Log in' %}
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link text-white">
                <i class="fas fa-user-plus"></i> {% trans 'Register' %}
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            <div class="dropdown-custom">
              <a href="{% url 'cart:cart_detail' %}"
                class="nav-link text-white drop-btn">
                <i class="fas fa-shopping-cart"></i>
                $<span id="cart_price">{{ cart_total_price|floatformat:2 }}</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container py-5">
    {% block content %}
    {% endblock %}
  </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
    integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>

</body>
</html>